name: Check
on: push
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Schanya/product-catalog-graphql
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
